# Generated by Django 5.1.4 on 2025-02-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(default='#4F46E5', max_length=7)),
                ('icono', models.CharField(choices=[('clipboard', 'Lista'), ('calendar', 'Calendario'), ('star', 'Estrella'), ('heart', 'Corazón'), ('home', 'Casa'), ('book', 'Libro'), ('briefcase', 'Maletín'), ('academic-cap', 'Graduación')], default='clipboard', max_length=20)),
            ],
            options={
                'verbose_name': 'Tablero',
                'verbose_name_plural': 'Tableros',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
