# Generated by Django 5.1.4 on 2025-02-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='color',
            field=models.CharField(default='#4F46E5', max_length=7),
        ),
        migrations.AddField(
            model_name='tablero',
            name='icono',
            field=models.CharField(choices=[('clipboard', 'Lista'), ('calendar', 'Calendario'), ('star', 'Estrella'), ('heart', 'Corazón'), ('home', 'Casa'), ('book', 'Libro'), ('briefcase', 'Maletín'), ('academic-cap', 'Graduación')], default='clipboard', max_length=20),
        ),
    ]
