# Generated by Django 5.1.4 on 2024-12-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notificaciones_app', '0001_initial'),
        ('tareas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tareas_app.tarea'),
        ),
    ]
