# Generated by Django 5.1.4 on 2025-02-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('tarea_completada', 'Tarea Completada'), ('fecha_vencimiento', 'Fecha de Vencimiento Próxima'), ('tarea_vencida', 'Tarea Vencida')], max_length=20),
        ),
    ]
