# Generated by Django 5.1.4 on 2025-02-19 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros_app', '0001_initial'),
        ('tareas_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tablero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='tableros_app.tablero'),
        ),
    ]
